# Generated by Django 4.1.4 on 2022-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
